#!/bin/bash

echo "=== ПРОВЕРКА СЕКРЕТОВ GITHUB ==="
echo ""
echo "Убедись, что в GitHub Actions Secrets добавлены:"
echo ""
echo "┌────────────────────┬──────────────────────────────────┐"
echo "│ Secret             │ Описание                         │"
echo "├────────────────────┼──────────────────────────────────┤"
echo "│ SECRET_KEY         │ Django secret key                │"
echo "│ DB_NAME            │ Имя базы данных                  │"
echo "│ DB_USER            │ Пользователь БД                  │"
echo "│ DB_PASSWORD        │ Пароль БД                        │"
echo "│ DB_HOST            │ Хост БД (обычно db)              │"
echo "│ DB_PORT            │ Порт БД (5432)                   │"
echo "│ SERVER_HOST        │ IP адрес сервера                 │"
echo "│ SERVER_USER        │ Имя пользователя на сервере      │"
echo "│ SSH_PRIVATE_KEY    │ Приватный SSH ключ               │"
echo "└────────────────────┴──────────────────────────────────┘"
echo ""
echo "Ссылка для добавления секретов:"
echo "https://github.com/ZhannaIvanova10/my-education-project/settings/secrets/actions"
